name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Generate version.py
        shell: bash
        run: |
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "__version__ = '${GITHUB_REF_NAME}'" > src/version.py
          echo "__build_date__ = '${BUILD_DATE}'" >> src/version.py
          echo "__commit__ = '${GITHUB_SHA}'" >> src/version.py
          echo "__is_package__ = True" >> src/version.py

      - name: Install npm deps
        run: npm ci
      
      - name: Build Tailwind
        run: |
          npx tailwindcss -c tailwind.config.js -i ./static/src/input.css -o ./static/dist/output.css --minify

      - name: Build
        run: pyinstaller --name="divera-print-kiel" --add-data=templates:templates --add-data=static:static --onedir src/main.py

      - name: Copy env example
        run: |
          python -c "import shutil; shutil.copy('.env.example', 'dist/divera-print-kiel/.env')"

      - name: Zip build
        run: |
          python -c "import shutil; shutil.make_archive('dist/divera-print-kiel-${{ matrix.os }}', 'zip', 'dist/divera-print-kiel')"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
